// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: internal/http/rpc/pb/dindin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EatingTomorrowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlackUID string `protobuf:"bytes,1,opt,name=SlackUID,proto3" json:"SlackUID,omitempty"`
}

func (x *EatingTomorrowRequest) Reset() {
	*x = EatingTomorrowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EatingTomorrowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EatingTomorrowRequest) ProtoMessage() {}

func (x *EatingTomorrowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EatingTomorrowRequest.ProtoReflect.Descriptor instead.
func (*EatingTomorrowRequest) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{0}
}

func (x *EatingTomorrowRequest) GetSlackUID() string {
	if x != nil {
		return x.SlackUID
	}
	return ""
}

type EatingTomorrowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EatingTomorrowResponse) Reset() {
	*x = EatingTomorrowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EatingTomorrowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EatingTomorrowResponse) ProtoMessage() {}

func (x *EatingTomorrowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EatingTomorrowResponse.ProtoReflect.Descriptor instead.
func (*EatingTomorrowResponse) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{1}
}

type PingMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingMessage) Reset() {
	*x = PingMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMessage) ProtoMessage() {}

func (x *PingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMessage.ProtoReflect.Descriptor instead.
func (*PingMessage) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{2}
}

func (x *PingMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMembersRequest) Reset() {
	*x = GetMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersRequest) ProtoMessage() {}

func (x *GetMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersRequest.ProtoReflect.Descriptor instead.
func (*GetMembersRequest) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{3}
}

type GetMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName   string `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName    string `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	RealName    string `protobuf:"bytes,3,opt,name=realName,proto3" json:"realName,omitempty"`
	DisplayName string `protobuf:"bytes,4,opt,name=displayName,proto3" json:"displayName,omitempty"`
	SlackUID    string `protobuf:"bytes,5,opt,name=slackUID,proto3" json:"slackUID,omitempty"`
}

func (x *GetMembersResponse) Reset() {
	*x = GetMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersResponse) ProtoMessage() {}

func (x *GetMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersResponse.ProtoReflect.Descriptor instead.
func (*GetMembersResponse) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{4}
}

func (x *GetMembersResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetMembersResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *GetMembersResponse) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *GetMembersResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GetMembersResponse) GetSlackUID() string {
	if x != nil {
		return x.SlackUID
	}
	return ""
}

type WeeklyUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WeeklyUpdateRequest) Reset() {
	*x = WeeklyUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeeklyUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyUpdateRequest) ProtoMessage() {}

func (x *WeeklyUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyUpdateRequest.ProtoReflect.Descriptor instead.
func (*WeeklyUpdateRequest) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{5}
}

type WeeklyUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WeeklyUpdateResponse) Reset() {
	*x = WeeklyUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeeklyUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyUpdateResponse) ProtoMessage() {}

func (x *WeeklyUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyUpdateResponse.ProtoReflect.Descriptor instead.
func (*WeeklyUpdateResponse) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{6}
}

type CookingDay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day      int32  `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	Month    int32  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Year     int32  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	SlackUID string `protobuf:"bytes,4,opt,name=slackUID,proto3" json:"slackUID,omitempty"`
}

func (x *CookingDay) Reset() {
	*x = CookingDay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CookingDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CookingDay) ProtoMessage() {}

func (x *CookingDay) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CookingDay.ProtoReflect.Descriptor instead.
func (*CookingDay) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{7}
}

func (x *CookingDay) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *CookingDay) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *CookingDay) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CookingDay) GetSlackUID() string {
	if x != nil {
		return x.SlackUID
	}
	return ""
}

type AssignCooksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CookingDays []*CookingDay `protobuf:"bytes,1,rep,name=CookingDays,proto3" json:"CookingDays,omitempty"`
}

func (x *AssignCooksRequest) Reset() {
	*x = AssignCooksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignCooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignCooksRequest) ProtoMessage() {}

func (x *AssignCooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignCooksRequest.ProtoReflect.Descriptor instead.
func (*AssignCooksRequest) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{8}
}

func (x *AssignCooksRequest) GetCookingDays() []*CookingDay {
	if x != nil {
		return x.CookingDays
	}
	return nil
}

type AssignCooksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AssignCooksResponse) Reset() {
	*x = AssignCooksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignCooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignCooksResponse) ProtoMessage() {}

func (x *AssignCooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignCooksResponse.ProtoReflect.Descriptor instead.
func (*AssignCooksResponse) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{9}
}

var File_internal_http_rpc_pb_dindin_proto protoreflect.FileDescriptor

var file_internal_http_rpc_pb_dindin_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x33, 0x0a, 0x15, 0x45, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x54, 0x6f, 0x6d, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x53, 0x6c, 0x61, 0x63, 0x6b, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x53, 0x6c, 0x61, 0x63, 0x6b, 0x55, 0x49, 0x44, 0x22, 0x18, 0x0a, 0x16,
	0x45, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x6d, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0xa8, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6c, 0x61, 0x63, 0x6b, 0x55, 0x49, 0x44, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6c, 0x61, 0x63, 0x6b, 0x55, 0x49, 0x44, 0x22,
	0x15, 0x0a, 0x13, 0x57, 0x65, 0x65, 0x6b, 0x6c, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x57, 0x65, 0x65, 0x6b, 0x6c, 0x79,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x64,
	0x0a, 0x0a, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d,
	0x6f, 0x6e, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6c, 0x61, 0x63,
	0x6b, 0x55, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6c, 0x61, 0x63,
	0x6b, 0x55, 0x49, 0x44, 0x22, 0x46, 0x0a, 0x12, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x43, 0x6f,
	0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x0b, 0x43, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x79, 0x52,
	0x0b, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x79, 0x73, 0x22, 0x15, 0x0a, 0x13,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0xcd, 0x02, 0x0a, 0x0c, 0x53, 0x6c, 0x61, 0x63, 0x6b, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x49, 0x0a, 0x0e, 0x45, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x6f,
	0x6d, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x54, 0x6f, 0x6d, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x6d,
	0x6f, 0x72, 0x72, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x2a, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x69,
	0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x43, 0x0a, 0x0c,
	0x57, 0x65, 0x65, 0x6b, 0x6c, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x70,
	0x62, 0x2e, 0x57, 0x65, 0x65, 0x6b, 0x6c, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x65, 0x65, 0x6b, 0x6c,
	0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x40, 0x0a, 0x0b, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6f, 0x6b, 0x73,
	0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6f, 0x6b,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x64, 0x64, 0x72, 0x69, 0x74, 0x7a, 0x65, 0x6e, 0x68, 0x6f, 0x66, 0x66, 0x2f, 0x64,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x68,
	0x74, 0x74, 0x70, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_http_rpc_pb_dindin_proto_rawDescOnce sync.Once
	file_internal_http_rpc_pb_dindin_proto_rawDescData = file_internal_http_rpc_pb_dindin_proto_rawDesc
)

func file_internal_http_rpc_pb_dindin_proto_rawDescGZIP() []byte {
	file_internal_http_rpc_pb_dindin_proto_rawDescOnce.Do(func() {
		file_internal_http_rpc_pb_dindin_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_http_rpc_pb_dindin_proto_rawDescData)
	})
	return file_internal_http_rpc_pb_dindin_proto_rawDescData
}

var file_internal_http_rpc_pb_dindin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_http_rpc_pb_dindin_proto_goTypes = []interface{}{
	(*EatingTomorrowRequest)(nil),  // 0: pb.EatingTomorrowRequest
	(*EatingTomorrowResponse)(nil), // 1: pb.EatingTomorrowResponse
	(*PingMessage)(nil),            // 2: pb.PingMessage
	(*GetMembersRequest)(nil),      // 3: pb.GetMembersRequest
	(*GetMembersResponse)(nil),     // 4: pb.GetMembersResponse
	(*WeeklyUpdateRequest)(nil),    // 5: pb.WeeklyUpdateRequest
	(*WeeklyUpdateResponse)(nil),   // 6: pb.WeeklyUpdateResponse
	(*CookingDay)(nil),             // 7: pb.CookingDay
	(*AssignCooksRequest)(nil),     // 8: pb.AssignCooksRequest
	(*AssignCooksResponse)(nil),    // 9: pb.AssignCooksResponse
}
var file_internal_http_rpc_pb_dindin_proto_depIdxs = []int32{
	7, // 0: pb.AssignCooksRequest.CookingDays:type_name -> pb.CookingDay
	0, // 1: pb.SlackActions.EatingTomorrow:input_type -> pb.EatingTomorrowRequest
	2, // 2: pb.SlackActions.Ping:input_type -> pb.PingMessage
	3, // 3: pb.SlackActions.GetMembers:input_type -> pb.GetMembersRequest
	5, // 4: pb.SlackActions.WeeklyUpdate:input_type -> pb.WeeklyUpdateRequest
	8, // 5: pb.SlackActions.AssignCooks:input_type -> pb.AssignCooksRequest
	1, // 6: pb.SlackActions.EatingTomorrow:output_type -> pb.EatingTomorrowResponse
	2, // 7: pb.SlackActions.Ping:output_type -> pb.PingMessage
	4, // 8: pb.SlackActions.GetMembers:output_type -> pb.GetMembersResponse
	6, // 9: pb.SlackActions.WeeklyUpdate:output_type -> pb.WeeklyUpdateResponse
	9, // 10: pb.SlackActions.AssignCooks:output_type -> pb.AssignCooksResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_http_rpc_pb_dindin_proto_init() }
func file_internal_http_rpc_pb_dindin_proto_init() {
	if File_internal_http_rpc_pb_dindin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_http_rpc_pb_dindin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EatingTomorrowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_http_rpc_pb_dindin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EatingTomorrowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_http_rpc_pb_dindin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_http_rpc_pb_dindin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_http_rpc_pb_dindin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_http_rpc_pb_dindin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeeklyUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_http_rpc_pb_dindin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeeklyUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_http_rpc_pb_dindin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CookingDay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_http_rpc_pb_dindin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignCooksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_http_rpc_pb_dindin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignCooksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_http_rpc_pb_dindin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_http_rpc_pb_dindin_proto_goTypes,
		DependencyIndexes: file_internal_http_rpc_pb_dindin_proto_depIdxs,
		MessageInfos:      file_internal_http_rpc_pb_dindin_proto_msgTypes,
	}.Build()
	File_internal_http_rpc_pb_dindin_proto = out.File
	file_internal_http_rpc_pb_dindin_proto_rawDesc = nil
	file_internal_http_rpc_pb_dindin_proto_goTypes = nil
	file_internal_http_rpc_pb_dindin_proto_depIdxs = nil
}
