// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: internal/http/rpc/pb/dindin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{0}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName   string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName    string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	RealName    string `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	DisplayName string `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Slack_UID   string `protobuf:"bytes,5,opt,name=slack_UID,json=slackUID,proto3" json:"slack_UID,omitempty"`
}

func (x *GetMembersResponse) Reset() {
	*x = GetMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersResponse) ProtoMessage() {}

func (x *GetMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersResponse.ProtoReflect.Descriptor instead.
func (*GetMembersResponse) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{1}
}

func (x *GetMembersResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetMembersResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *GetMembersResponse) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *GetMembersResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GetMembersResponse) GetSlack_UID() string {
	if x != nil {
		return x.Slack_UID
	}
	return ""
}

type Cooking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day       int32  `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	Month     int32  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Year      int32  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Slack_UID string `protobuf:"bytes,4,opt,name=slack_UID,json=slackUID,proto3" json:"slack_UID,omitempty"`
}

func (x *Cooking) Reset() {
	*x = Cooking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cooking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cooking) ProtoMessage() {}

func (x *Cooking) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cooking.ProtoReflect.Descriptor instead.
func (*Cooking) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{2}
}

func (x *Cooking) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *Cooking) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *Cooking) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Cooking) GetSlack_UID() string {
	if x != nil {
		return x.Slack_UID
	}
	return ""
}

type AssignCooksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cookings []*Cooking `protobuf:"bytes,1,rep,name=Cookings,proto3" json:"Cookings,omitempty"`
}

func (x *AssignCooksRequest) Reset() {
	*x = AssignCooksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignCooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignCooksRequest) ProtoMessage() {}

func (x *AssignCooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignCooksRequest.ProtoReflect.Descriptor instead.
func (*AssignCooksRequest) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{3}
}

func (x *AssignCooksRequest) GetCookings() []*Cooking {
	if x != nil {
		return x.Cookings
	}
	return nil
}

type EmptyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{4}
}

type UpcomingCooksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DaysWanted int64 `protobuf:"varint,1,opt,name=days_wanted,json=daysWanted,proto3" json:"days_wanted,omitempty"`
}

func (x *UpcomingCooksRequest) Reset() {
	*x = UpcomingCooksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpcomingCooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpcomingCooksRequest) ProtoMessage() {}

func (x *UpcomingCooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpcomingCooksRequest.ProtoReflect.Descriptor instead.
func (*UpcomingCooksRequest) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{5}
}

func (x *UpcomingCooksRequest) GetDaysWanted() int64 {
	if x != nil {
		return x.DaysWanted
	}
	return 0
}

type Cook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CookingTime     int64  `protobuf:"varint,1,opt,name=cooking_time,json=cookingTime,proto3" json:"cooking_time,omitempty"`
	ChefSlack_UID   string `protobuf:"bytes,2,opt,name=chef_slack_UID,json=chefSlackUID,proto3" json:"chef_slack_UID,omitempty"`
	MealDescription string `protobuf:"bytes,3,opt,name=meal_description,json=mealDescription,proto3" json:"meal_description,omitempty"`
	SlackMessage_ID string `protobuf:"bytes,4,opt,name=slack_message_ID,json=slackMessageID,proto3" json:"slack_message_ID,omitempty"`
	FirstName       string `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName        string `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
}

func (x *Cook) Reset() {
	*x = Cook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cook) ProtoMessage() {}

func (x *Cook) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cook.ProtoReflect.Descriptor instead.
func (*Cook) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{6}
}

func (x *Cook) GetCookingTime() int64 {
	if x != nil {
		return x.CookingTime
	}
	return 0
}

func (x *Cook) GetChefSlack_UID() string {
	if x != nil {
		return x.ChefSlack_UID
	}
	return ""
}

func (x *Cook) GetMealDescription() string {
	if x != nil {
		return x.MealDescription
	}
	return ""
}

func (x *Cook) GetSlackMessage_ID() string {
	if x != nil {
		return x.SlackMessage_ID
	}
	return ""
}

func (x *Cook) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Cook) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type UpcomingCooksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cooks []*Cook `protobuf:"bytes,1,rep,name=Cooks,proto3" json:"Cooks,omitempty"`
}

func (x *UpcomingCooksResponse) Reset() {
	*x = UpcomingCooksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpcomingCooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpcomingCooksResponse) ProtoMessage() {}

func (x *UpcomingCooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_http_rpc_pb_dindin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpcomingCooksResponse.ProtoReflect.Descriptor instead.
func (*UpcomingCooksResponse) Descriptor() ([]byte, []int) {
	return file_internal_http_rpc_pb_dindin_proto_rawDescGZIP(), []int{7}
}

func (x *UpcomingCooksResponse) GetCooks() []*Cook {
	if x != nil {
		return x.Cooks
	}
	return nil
}

var File_internal_http_rpc_pb_dindin_proto protoreflect.FileDescriptor

var file_internal_http_rpc_pb_dindin_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x28, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0xad, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x55, 0x49,
	0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6c, 0x61, 0x63, 0x6b, 0x55, 0x49,
	0x44, 0x22, 0x62, 0x0a, 0x07, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03,
	0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d,
	0x6f, 0x6e, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6c, 0x61, 0x63,
	0x6b, 0x5f, 0x55, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6c, 0x61,
	0x63, 0x6b, 0x55, 0x49, 0x44, 0x22, 0x3d, 0x0a, 0x12, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x43,
	0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x08, 0x43,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x43, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x37, 0x0a, 0x14, 0x55, 0x70, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67,
	0x43, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x64, 0x61, 0x79, 0x73, 0x5f, 0x77, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x64, 0x61, 0x79, 0x73, 0x57, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x22, 0xe0, 0x01,
	0x0a, 0x04, 0x43, 0x6f, 0x6f, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x68, 0x65,
	0x66, 0x5f, 0x73, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x63, 0x68, 0x65, 0x66, 0x53, 0x6c, 0x61, 0x63, 0x6b, 0x55, 0x49, 0x44, 0x12,
	0x29, 0x0a, 0x10, 0x6d, 0x65, 0x61, 0x6c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6d, 0x65, 0x61, 0x6c, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x6c,
	0x61, 0x63, 0x6b, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x49, 0x44, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x6c, 0x61, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x44, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x37, 0x0a, 0x15, 0x55, 0x70, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6f, 0x6b,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x43, 0x6f, 0x6f,
	0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f,
	0x6f, 0x6b, 0x52, 0x05, 0x43, 0x6f, 0x6f, 0x6b, 0x73, 0x32, 0xe9, 0x02, 0x0a, 0x0c, 0x53, 0x6c,
	0x61, 0x63, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x36, 0x0a, 0x0e, 0x45, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x6d, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x12, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x00, 0x12, 0x2c, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3a, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x34, 0x0a, 0x0c,
	0x57, 0x65, 0x65, 0x6b, 0x6c, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x00, 0x12, 0x39, 0x0a, 0x0b, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6f, 0x6b,
	0x73, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6f,
	0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a,
	0x0d, 0x55, 0x70, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x18,
	0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6f, 0x6b,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70,
	0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x64, 0x72, 0x69, 0x74, 0x7a, 0x65, 0x6e, 0x68, 0x6f, 0x66, 0x66,
	0x2f, 0x64, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_http_rpc_pb_dindin_proto_rawDescOnce sync.Once
	file_internal_http_rpc_pb_dindin_proto_rawDescData = file_internal_http_rpc_pb_dindin_proto_rawDesc
)

func file_internal_http_rpc_pb_dindin_proto_rawDescGZIP() []byte {
	file_internal_http_rpc_pb_dindin_proto_rawDescOnce.Do(func() {
		file_internal_http_rpc_pb_dindin_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_http_rpc_pb_dindin_proto_rawDescData)
	})
	return file_internal_http_rpc_pb_dindin_proto_rawDescData
}

var file_internal_http_rpc_pb_dindin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_http_rpc_pb_dindin_proto_goTypes = []interface{}{
	(*PingResponse)(nil),          // 0: pb.PingResponse
	(*GetMembersResponse)(nil),    // 1: pb.GetMembersResponse
	(*Cooking)(nil),               // 2: pb.Cooking
	(*AssignCooksRequest)(nil),    // 3: pb.AssignCooksRequest
	(*EmptyMessage)(nil),          // 4: pb.EmptyMessage
	(*UpcomingCooksRequest)(nil),  // 5: pb.UpcomingCooksRequest
	(*Cook)(nil),                  // 6: pb.Cook
	(*UpcomingCooksResponse)(nil), // 7: pb.UpcomingCooksResponse
}
var file_internal_http_rpc_pb_dindin_proto_depIdxs = []int32{
	2, // 0: pb.AssignCooksRequest.Cookings:type_name -> pb.Cooking
	6, // 1: pb.UpcomingCooksResponse.Cooks:type_name -> pb.Cook
	4, // 2: pb.SlackActions.EatingTomorrow:input_type -> pb.EmptyMessage
	4, // 3: pb.SlackActions.Ping:input_type -> pb.EmptyMessage
	4, // 4: pb.SlackActions.GetMembers:input_type -> pb.EmptyMessage
	4, // 5: pb.SlackActions.WeeklyUpdate:input_type -> pb.EmptyMessage
	3, // 6: pb.SlackActions.AssignCooks:input_type -> pb.AssignCooksRequest
	5, // 7: pb.SlackActions.UpcomingCooks:input_type -> pb.UpcomingCooksRequest
	4, // 8: pb.SlackActions.EatingTomorrow:output_type -> pb.EmptyMessage
	0, // 9: pb.SlackActions.Ping:output_type -> pb.PingResponse
	1, // 10: pb.SlackActions.GetMembers:output_type -> pb.GetMembersResponse
	4, // 11: pb.SlackActions.WeeklyUpdate:output_type -> pb.EmptyMessage
	4, // 12: pb.SlackActions.AssignCooks:output_type -> pb.EmptyMessage
	7, // 13: pb.SlackActions.UpcomingCooks:output_type -> pb.UpcomingCooksResponse
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_http_rpc_pb_dindin_proto_init() }
func file_internal_http_rpc_pb_dindin_proto_init() {
	if File_internal_http_rpc_pb_dindin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_http_rpc_pb_dindin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_http_rpc_pb_dindin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_http_rpc_pb_dindin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cooking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_http_rpc_pb_dindin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignCooksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_http_rpc_pb_dindin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_http_rpc_pb_dindin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpcomingCooksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_http_rpc_pb_dindin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_http_rpc_pb_dindin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpcomingCooksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_http_rpc_pb_dindin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_http_rpc_pb_dindin_proto_goTypes,
		DependencyIndexes: file_internal_http_rpc_pb_dindin_proto_depIdxs,
		MessageInfos:      file_internal_http_rpc_pb_dindin_proto_msgTypes,
	}.Build()
	File_internal_http_rpc_pb_dindin_proto = out.File
	file_internal_http_rpc_pb_dindin_proto_rawDesc = nil
	file_internal_http_rpc_pb_dindin_proto_goTypes = nil
	file_internal_http_rpc_pb_dindin_proto_depIdxs = nil
}
