[http]
# url represents the address the dinny server will listen on.
url = "localhost:7777"

[db]
# the data source name (dsn) represents the path to your db.
dsn = "~/dinny.db"

# These values represent the slack app's configuration values and can be retrieved from the app's Slack API homepage.
[slack]
botSigningKey = ""
appID = ""
clientID = ""
clientSecret= ""
signingSecret = ""
channelID = ""
